project_1/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'


urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")

]

project_1/movies/urls.py
from django.urls import path
from . import views
app_name = 'movies'


urlpatterns = [
    path('', views.movies_list, name="list"),
    path('review/', views.create_review, name="review"),
    path('signed_in/', views.movies_list_signed_in, name="signed_in"),
    path('signed_in/<slug:slug>/', views.movie_detail_signed_in, name="details_signed_in"),
    path('<slug:slug>/', views.movie_detail, name="detail")
]

project_1/project_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from movies import views
from django.conf.urls.static import static
from django.conf import settings
from movies import views as movie_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('', movie_views.movies_list, name="home")
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_1/accounts/models.py
from django.db import models

# Create your models here.

project_1/movies/models.py
from django.db import models
from django.contrib.auth.models import User


class Movie(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    general = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    text = models.TextField()
    movie = models.ForeignKey(Movie, related_name="reviews", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

project_1/movies/forms.py
from django import forms
from . import models


class CreateReview(forms.ModelForm):
    class Meta:
        model = models.Review
        fields = ['movie', 'text']

project_1/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("movies:signed_in")
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {"form": form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("movies:signed_in")
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {"form": form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("movies:list")

project_1/movies/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Movie, Review
from django.contrib.auth.decorators import login_required
from . import forms


def movies_list(request):
    movies = Movie.objects.all().order_by('date')
    return render(request, 'movies/movies_list.html', {"movies": movies})


def movies_list_signed_in(request):
    movies = Movie.objects.all().order_by('date')
    return render(request, 'movies/signed_in.html', {"movies": movies})


def movie_detail(request, slug):
    movie = Movie.objects.get(slug=slug)
    # review = Review.objects.all().order_by('date')
    return render(request, 'movies/movies_detail.html', {"movie": movie})


def movie_detail_signed_in(request, slug):
    movie = Movie.objects.get(slug=slug)
    return render(request, 'movies/movies_detail_signed_in.html', {"movie": movie})


@login_required(login_url="/accounts/login/")
def create_review(request):
    if request.method == "POST":
        form = forms.CreateReview(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('movies:list')
    else:
        form = forms.CreateReview()
    return render(request, 'movies/create_review.html', {"form": form})

project_1/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="sidebar">
    <div class="home-pic">
    <h1><a href="{% url 'movies:list' %}"><img src="{% static 'home.png' %}" style="width:30px; height:30px;"></a></h1>
    </div>
</div>
<h1 style="text-align:center; color:#907878;">-Login-</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
</form>
{% endblock %}

project_1/templates/accounts/logout.html
{% extends 'base_layout.html' %}
{% block content %}


<h1>Logout</h1>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Logout">
</form>
{% endblock %}

project_1/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="sidebar">
    <div class="home-pic">
    <h1><a href="{% url 'movies:list' %}"><img src="{% static 'home.png' %}" style="width:30px; height:30px;"></a></h1>
    </div>
</div>
<h1 style="text-align:center; color:#907878;">-Signup-</h1>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Signup">
</form>

{% endblock %}

project_1/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>movies list</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<h1></h1>
<body>
<a href="{% url 'home' %}"></a>
<div class="wrapper">
<!--    <nav>-->
<!--        <ul>-->
<!--        <li><form class="logout-link" action="{% url 'accounts:logout' %}" method="post">-->
<!--            {% csrf_token %}-->
<!--            <input type="submit" value="Logout">-->
<!--        </form></li>-->
<!--        <li><form class="login-link" action="{% url 'accounts:login' %}" method="post">-->
<!--            {% csrf_token %}-->
<!--            <input type="submit" value="Login">-->
<!--        </form></li>-->
<!--        <li><form class="signup-link" action="{% url 'accounts:signup' %}" method="post">-->
<!--            {% csrf_token %}-->
<!--            <input type="submit" value="Signup">-->
<!--        </form></li>-->
<!--        </ul>-->
<!--    </nav>-->
    <div class="sidebar"></div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

project_1/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>still working</title>
</head>
<h1>hi</h1>
<body>

</body>
</html>

project_1/templates/movies/create_review.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<li><form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Logout">
 </form></li>
<div class="sidebar">
    <div class="home">
    <h1><a href="{% url 'movies:signed_in' %}"><img src="{% static 'home.png' %}" style="width:30px; height:30px; margin-left:10px;"></a></h1>
    </div>
</div>
<h1 style="text-align:center; color:#907878;">Tell us what you think...</h1>
<h1><a href="{% url 'movies:list' %}"><img src="{% static 'home.png' %}" style="width:40px; height:40px;"></a></h1>
<form class="site-form" action="{% url 'movies:review' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

project_1/templates/movies/movies_detail.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static %}
<nav>
  <ul>
        <li><form class="login-link" action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Login">
        </form></li>
        <li><form class="signup-link" action="{% url 'accounts:signup' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Signup">
        </form></li>
  </ul></nav>
<div class="sidebar">
    <div class="home-pic">
<h1><a href="{% url 'movies:list' %}"><img src="{% static 'home.png' %}" style="width:30px; height:30px;"></a></h1>
    </div>
</div>
<div class="movie-detail">
    <div class="movie">
        <h1 style="color:#EEDDDD;">{{ movie.title }}</h1><br/>
        <h3 style="color:#EADADA; font-weight:lighter;">{{ movie.description }}</h3><br/>
        <img class="movie-img" src="{{ movie.thumb.url }}" style="width:200px; height:300px;">
        <br/><br/>
        <h4 style="color:#EADADA; font-weight:lighter;">{{ movie.general }}</h4>
    </div>
</div>
<br/><br/>
<hr>

<div class="comments">
    <h2>Reviews</h2>
    <br/>
    {% if movie.reviews.all %}
        {% for review in movie.reviews.all %}
    <div class="comment">
        <strong>
            {{ review.user }}-
            {{ review.date }}
        </strong>
    </div>

            {{ review.text }}<br/><br/>
        {% endfor %}
    {% else %}
        <h3>-No reviews yet-</h3>

    {% endif %}
{% endblock %}

project_1/templates/movies/movies_detail_signed_in.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static %}


<nav>
 <li><form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Logout">
 </form></li>
</nav>
<div class="sidebar">
    <div class="home">
<h1><a href="{% url 'movies:signed_in' %}"><img src="{% static 'home.png' %}" style="width:30px; height:30px;"></a></h1>
    </div>
</div>
<div class="movie-detail">
    <div class="movie">
        <h1 style="color:#EEDDDD;">{{ movie.title }}</h1><br/>
        <h3 style="color:#EADADA; font-weight:lighter;">{{ movie.description }}</h3><br/>
        <img class="movie-img" src="{{ movie.thumb.url }}" style="width:200px; height:300px;">
        <br/><br/>
        <h4 style="color:#EADADA; font-weight:lighter;">{{ movie.general }}</h4>
    </div>
</div>
<br/><br/>
<hr>

<div class="comments">
    <h2>Reviews</h2>
    <br/>
    {% if movie.reviews.all %}
        {% for review in movie.reviews.all %}
    <div class="comment">
        <strong>
            {{ review.user }}-
            {{ review.date }}
        </strong>
    </div>

            {{ review.text }}<br/><br/>
        {% endfor %}
    {% else %}
        <h3>-No reviews yet-</h3>

    {% endif %}

<ul><form class="add-review" action="{% url 'movies:review' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Add Review">
 </form></ul>

{% endblock %}

project_1/templates/movies/movies_list.html
{% extends 'base_layout.html' %}
{% block content %}
<nav>
  <ul>
        <li><form class="login-link" action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Login">
        </form></li>
        <li><form class="signup-link" action="{% url 'accounts:signup' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Signup">
        </form></li>
  </ul></nav>
<div class="movies">
    {% for movie in movies %}
    <div class="movie">
        <h2><a href="{% url 'movies:detail' slug=movie.slug %}"><img class="pic" src="{{ movie.thumb.url }}" style="width:200px; height:300px;"></a></h2>
    </div>
    {% endfor %}
</div>
{% endblock %}

project_1/templates/movies/signed_in.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static %}


 <li><form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Logout">
 </form></li>
<div class="movies">
    {% for movie in movies %}
    <div class="movie">
        <h2><a href="{% url 'movies:details_signed_in' slug=movie.slug %}"><img class="pic" src="{{ movie.thumb.url }}" style="width:200px; height:300px;"></a></h2>
    </div>
    {% endfor %}
</div>
{% endblock %}